language: java
jdk:
    - openjdk8
before_install:
    - chmod +x spotify-clone-frontend/gradlew
    - chmod +x spotify-clone-frontend/gradle/wrapper/gradle-wrapper.jar
script:
    - ./spotify-clone-frontend/gradlew build
